name: "Composer"
description: "Setup Composer"

inputs:
  command:
    required: false
    type: string
    default: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable"

runs:
  using: "composite"

  steps:
    - name: "Get Composer cache directory"
      id: "composercache"
      shell: "bash"
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_STATE

    - name: "Cache PHP dependencies"
      uses: "actions/cache@v3"
      with:
        path: "${{ steps.composercache.outputs.dir }}"
        key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}"
        restore-keys: "${{ runner.os }}-composer-"

    - name: "Install Composer dependencies"
      shell: "bash"
      run: "${{ inputs.command }}"