name: Codesniffer

on:
  workflow_call:
    inputs:
      make:
        required: false
        type: string
        default: "cs"

      php:
        required: false
        type: string
        default: "8.1"

      composer:
        required: false
        type: string
        default: "composer install --no-interaction --no-progress --prefer-dist"

jobs:
  codesniffer:
    name: "Codesniffer (${{ inputs.php }})"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "PHP"
        uses: "contributte/.github/.github/actions/setup-php@master"
        with:
          php: "${{ inputs.php }}"
          tools: "composer:v2,cs2pr"

      - name: "Composer"
        uses: "contributte/.github/.github/actions/setup-composer@master"
        with:
          command: "${{ inputs.composer }}"

      - name: "Coding Standard"
        run: "make ${{ inputs.make }}"
