name: Nette Tester

on:
  workflow_call:
    inputs:
      makefile:
        required: false
        type: string
        default: "tests"

      php:
        required: false
        type: string
        default: "8.1"

      composer:
        required: false
        type: string
        default: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable"

      coverage:
        required: false
        type: boolean
        default: false

      mysql:
        required: false
        type: string
        default: "5.7"

      database:
        required: false
        type: string
        default: "tests"

jobs:
  tests:
    name: "Nette Tester ${{ inputs.php }} / MySQL ${{ inputs.mariadb }}"
    runs-on: "ubuntu-latest"

    services:
      mysql:
        image: "mysql:${{ inputs.mysql }}"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: "${{ inputs.database }}"
        ports:
          - 3306:3306

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "PHP"
        uses: "contributte/.github/.github/actions/setup-php@v1"
        with:
          php: "${{ inputs.php }}"

      - name: "Composer"
        uses: "contributte/.github/.github/actions/setup-composer@v1"
        with:
          command: "${{ inputs.composer }}"

      - name: "Run Nette Tester"
        run: "make ${{ inputs.makefile }}"

      - name: "Coveralls.io"
        if: ${{ inputs.coverage == true }}
        env:
          CI_NAME: github
          CI: true
          COVERALLS_REPO_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.1/php-coveralls.phar
          php php-coveralls.phar --verbose --config tests/.coveralls.yml
