name: Phpstan

on:
  workflow_call:
    inputs:
      makefile:
        required: false
        type: string
        default: "phpstan"

      php:
        required: false
        type: string
        default: "8.1"

      composer:
        required: false
        type: string
        default: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable"

jobs:
  phpstan:
    name: "Phpstan (${{ inputs.php }})"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "PHP"
        uses: "contributte/.github/.github/actions/setup-php@v1"
        with:
          version: "${{ inputs.php }}"

      - name: "Composer"
        uses: "contributte/.github/.github/actions/setup-composer@v1"
        with:
          command: "${{ inputs.composer }}"

      - name: "PHPStan"
        run: "make ${{ inputs.makefile }}"
