name: Phpstan

on:
  workflow_call:
    inputs:
      make:
        required: false
        type: string
        default: "phpstan"

      php:
        required: false
        type: string
        default: "8.1"

      composer:
        required: false
        type: string
        default: "composer install --no-interaction --no-progress --prefer-dist"

jobs:
  phpstan:
    name: "Phpstan (${{ inputs.php }})"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "PHP"
        uses: "contributte/.github/.github/actions/setup-php@master"
        with:
          php: "${{ inputs.php }}"

      - name: "Composer"
        uses: "contributte/.github/.github/actions/setup-composer@master"
        with:
          command: "${{ inputs.composer }}"

      - name: "PHPStan"
        run: "make ${{ inputs.make }}"
