name: Phpunit

on:
  workflow_call:
    inputs:
      make:
        required: false
        type: string
        default: "coverage"

      php:
        required: false
        type: string
        default: "8.1"

      composer:
        required: false
        type: string
        default: "composer install --no-interaction --no-progress --prefer-dist --prefer-stable"

jobs:
  tests:
    name: "Nette Tester (${{ inputs.php }})"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "PHP"
        uses: "contributte/.github/.github/actions/setup-php@master"
        with:
          php: "${{ inputs.php }}"

      - name: "Composer"
        uses: "contributte/.github/.github/actions/setup-composer@master"
        with:
          command: "${{ inputs.composer }}"

      - name: "Setup problem matchers for PHPUnit"
        shell: "bash"
        run: 'echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"'

      - name: "Run Phpunit"
        run: "make ${{ inputs.make }}"

      - name: "Coveralls.io"
        env:
          CI_NAME: github
          CI: true
          COVERALLS_REPO_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.3/php-coveralls.phar
          php php-coveralls.phar --verbose --config tests/.coveralls.yml
